name: Build and release electron

on: workflow_dispatch

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Build
        if: "!startsWith(matrix.os, 'macos')"
        run: yarn electron-pack
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build for Mac OS
        if: startsWith(matrix.os, 'macos')
        run: yarn electron-pack
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPW: ${{ secrets.APPLEIDPW }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
